[project]
name = "pyperformance_bm_sqlglot_v2"
requires-python = ">=3.7"
dependencies = [
    "pyperf@git+https://github.com/Yhg1s/pyperf@local-changes#egg=pyperf",
    "sqlglot_v2",
]
urls = {repository = "https://github.com/python/pyperformance"}
dynamic = ["version"]

[tool.pyperformance]
name = "sqlglot_v2_normalize"
extra_opts = ["normalize"]
